fabric01:
  hosts:
    apic1:
      apic_host: 172.16.109.70
      apic_username: admin
    n7k:
      nxos_host: 172.16.105.5
      nxos_username: admin
  vars:
    apic_use_proxy: no
    apic_validate_certs: no
    nxos_use_proxy: no
    nxos_topology:
      features:
        - nxapi
        - ospf
        - interface-vlan
        - lacp
        - lldp
      interface:
      - number: 1/19/1
        type: no switchport
        ip: 192.168.101.1/24
        admin_state: up
        vrf: autolab_pod1_epg1
      - number: 1/19/2
        type: no switchport
        ip: 192.168.102.1/24
        admin_state: up
        vrf: autolab_pod1_epg2
      - number: 1/19/3
        type: no switchport
        ip: 192.168.101.2/24
        admin_state: up
        vrf: autolab_pod2_epg1
      - number: 1/19/4
        type: no switchport 
        ip: 192.168.103.1/24
        admin_state: up
        vrf: autlab_pod2_epg3
    aci_topology:
      access_policy:
      - switch_policy_profile:
        - name: ansible-101
          leaf_selector:
          - name: Leaf101
            from: 101
            to: 101
          interface_selector_profile:
          - name: ansible_leaf101
        - name: ansible-111
          leaf_selector:
          - name: Leaf111
            from: 111
            to: 111
          interface_selector_profile:
          - name: ansible_leaf111
      - interface_policy_lldp:
        - name: LLDP_ON
          receive_state: 1
          transmit_state: 1
      - interface_policy_policy_group_access:
        - name: anisble_if_pg
          lldp: LLDP_ON
          aep: ansible_aep
      - interface_policy_profile:
        - name: ansible_leaf101
          interface_selector:
          - name: n7k_pod1
            int_card: 1
            int_to: 24
            int_from: 23
            policy_group: ansible_if_pg
            policy_group_type: accportgrp
        - name: ansible_leaf111
          interface_selector:
          - name: n7k_pod2
            int_card: 1
            int_to: 24
            int_from: 23
            policy_group: ansible_if_pg
            policy_group_type: accportgrp
      - vlan_pool:
        - name: ansible_pool
          alloc: static
          encap_block:
          - from: 3800
            to: 3899
      - aep:
        - name: ansible_aep
          domain: 
          - name: ansible_phydom
      - physical_domain:
        - name: ansible_phydom
          vlan_pool: ansible_pool
          vlan_pool_alloc: static

      tenant:
      - name: AutoLab
        description: ACI as Code. Made in Ansible 
        contract:
        - name: epg1_epg2
          scope: global
          subject:
          - name: allow_all
            filter:
            - name: ip
              entry:
              - name: ip
                ether_type: ip
        - name: epg2_epg3
          scope: global
          subject:
          - name: allow_all
            filter:
            - name: ip
              entry:
              - name: ip
                ether_type: ip
        - name: epg1_epg3
          scope: global
          subject:
          - name: allow_all
            filter:
            - name: ip
              entry:
              - name: ip
                ether_type: ip
        app:
        - name: APP1
          epg:
          - name: EPG1
            bd: BD1
            static_path:
            - pod: 1
              path: topology/pod-1/paths-101/pathep-[eth1/23]
              encap: vlan-3801
              mode: regular
            - pod: 2
              path: topology/pod-2/paths-111/pathep-[eth1/23]
              encap: vlan-3801
              mode: regular
            domain:
            - name: ansible_phydom
              type: phys
          - name: EPG2
            bd: BD2
            static_path:
            - pod: 1
              path: topology/pod-1/paths-101/pathep-[eth1/24]
              encap: vlan-3802
              mode: regular
            domain:
            - name: ansible_phydom
              type: phys
          - name: EPG3
            bd: BD3
            static_path:
            - pod: 2
              path: topology/pod-1/paths-111/pathep-[eth1/24]
              encap: vlan-3803
              mode: regular
            domain:
            - name: ansible_phydom
              type: phys
        bd:
        - name: BD1
          subnet: 
          - name: 192.168.101.254
            mask: 24
            scope: private
          vrf: VRF1
        - name: BD2
          subnet: 
          - name: 192.168.102.254
            mask: 24
            scope: private
          vrf: VRF1
        - name: BD3
          subnet:
          - name: 192.168.103.254
            mask: 24
            scope: private
          vrf: VRF3
        vrf:
        - name: VRF1
        - name: VRF3

# vim: ts=2: sw=2: et
